## Deliverable 3. Create a Travel Itinerary Map.

In [38]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [39]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv(r"C:\Users\sherr\Desktop\Case_Data_Bootcamp\World_Weather_Analysis\Vacation_Search\WeatherPy_vacation.csv")
vacation_df.head(30)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Puerto Ayora,EC,78.76,light rain,-0.7393,-90.3518,Finch Bay Galapagos Hotel
1,5,Vaini,TO,82.56,broken clouds,-21.2000,-175.2000,Keleti Beach Resort
2,7,Rikitea,PF,78.49,clear sky,-23.1203,-134.9692,People ThankYou
3,16,Georgetown,MY,82.33,few clouds,5.4112,100.3354,Cititel Penang
4,17,Hithadhoo,MV,82.51,scattered clouds,-0.6000,73.0833,Scoop Guest House
5,35,Kapaa,US,78.78,light rain,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
6,41,Maracaibo,VE,82.56,overcast clouds,10.6317,-71.6406,Motel Aladdin
7,45,Grajau,BR,75.72,overcast clouds,-5.8194,-46.1386,Hotel Confian√ßa
8,51,Acapulco,MX,85.82,clear sky,16.8634,-99.8901,HS Hotsson Smart Acapulco
9,56,Lorengau,PG,82.49,scattered clouds,-2.0226,147.2712,Lorengau Harbourside Hotel
10,61,Butaritari,KI,81.63,few clouds,3.0707,172.7902,Isles Sunset Lodge
11,64,Bathsheba,BB,81.21,scattered clouds,13.2167,-59.5167,Atlantis Hotel
12,67,Ugoofaaru,MV,83.93,overcast clouds,5.6667,73.0000,Ungoofaaru Inn
13,68,Kibala,TD,83.80,broken clouds,9.1104,18.3463,hotel safari
14,74,Manta,EC,85.78,scattered clouds,-0.9500,-80.7333,Balandra Hotel
15,75,San Patricio,US,88.16,few clouds,28.0170,-97.5169,"Motel 6 Sinton, TX"
16,77,Atuona,PF,79.75,clear sky,-9.8000,-139.0333,Villa Enata
17,82,Isangel,VU,80.71,overcast clouds,-19.5500,169.2667,Tanna Lodge
18,87,Souillac,MU,77.38,light rain,-20.5167,57.5167,Shanti Maurice Resort & Spa
19,90,Alofi,NU,84.09,broken clouds,-19.0595,-169.9187,Taloa Heights
20,93,Porto Novo,BJ,84.02,light rain,6.4965,2.6036,Tour Eiffel Hotel Benin
21,98,Saint George,US,84.43,clear sky,37.1041,-113.5841,Best Western Plus Abbey Inn
22,102,Hambantota,LK,75.54,few clouds,6.1241,81.1185,Bungalow 63
23,109,Le Port,RE,77.00,clear sky,-20.9373,55.2919,KORBEY D'OR OUEST
24,111,Hilo,US,81.28,moderate rain,19.7297,-155.0900,Hilo Hawaiian Hotel
25,116,Nabire,ID,76.80,moderate rain,-3.3667,135.4833,Hotel Nusantara I
26,119,Abu Zabad,SD,86.97,clear sky,12.3500,29.2500,ÿ≠ÿßŸÖÿØ ŸÖÿ≠ŸÖÿØ ŸÜŸàÿ±
27,121,Kavieng,PG,84.63,overcast clouds,-2.5744,150.7967,Nusa Island Retreat
28,123,Avarua,CK,82.45,scattered clouds,-21.2078,-159.7750,Paradise Inn
29,125,Touros,BR,79.84,broken clouds,-5.1989,-35.4608,INN NEW HORIZON

In [40]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<d1>
<dt>Hotel Name</dt><dd>{Hotel Name}<dd>
<dt>City</dt><dd>{City}<dd/>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp}<dd>
</d1>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [41]:
# 4a. Add a marker layer for each city to the map.
fig=gmaps.figure(center=(30,31),zoom_level=1.5)
marker_layer=gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [42]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"]=="Touros"]
vacation_end = vacation_df.loc[vacation_df["City"]=="Touros"]
vacation_stop1 = vacation_df.loc[vacation_df["City"]=="Cabedelo"]
vacation_stop2 = vacation_df.loc[vacation_df["City"]=="Maragogi"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"]=="Grajau"] 
vacation_stop1

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
112,429,Cabedelo,BR,81.27,broken clouds,-6.9811,-34.8339,Hotel Pigalle

In [57]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = (vacation_start.to_numpy()[0][5],vacation_start.to_numpy()[0][6])
end = (vacation_end.to_numpy()[0][5],vacation_end.to_numpy()[0][6])
stop1 = (vacation_stop1.to_numpy()[0][5],vacation_stop1.to_numpy()[0][6])
stop2 = (vacation_stop2.to_numpy()[0][5],vacation_stop2.to_numpy()[0][6])
stop3 = (vacation_stop3.to_numpy()[0][5],vacation_stop3.to_numpy()[0][6])
stop2

(-9.0122, -35.2225)

In [49]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig=gmaps.figure()
dlayer=gmaps.directions_layer(start, end, waypoints=[stop1,stop2,stop3], travel_mode="DRIVING")
fig.add_layer(dlayer)
fig

Figure(layout=FigureLayout(height='420px'))

In [51]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,125,Touros,BR,79.84,broken clouds,-5.1989,-35.4608,INN NEW HORIZON
1,429,Cabedelo,BR,81.27,broken clouds,-6.9811,-34.8339,Hotel Pigalle
2,608,Maragogi,BR,78.49,broken clouds,-9.0122,-35.2225,Salinas do Maragogi All Inclusive Resort
3,45,Grajau,BR,75.72,overcast clouds,-5.8194,-46.1386,Hotel Confian√ßa

In [52]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<d1>
<dt>Hotel Name</dt><dd>{Hotel Name}<dd>
<dt>City</dt><dd>{City}<dd/>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp}<dd>
</d1>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [56]:
# 11a. Add a marker layer for each city to the map.
fig=gmaps.figure(center=(-7,-38),zoom_level=5)
marker_layer=gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))